---
- name: Create public ip for Linux Web Servers
  local_action:
    module: azure_rm_publicipaddress
    resource_group: "{{ az_resourcegroup_name }}"
    allocation_method: "{{ az_public_ip_method }}"
    name: "{{ az_public_ip_name }}"
  register: r_azure_public_ip

- name: Create NIC for Linux Web servers
  local_action:
    module: azure_rm_networkinterface
    resource_group: "{{ az_resourcegroup_name }}"
    name: "{{ az_vm_nic_name }}"
    virtual_network: "{{ az_virtualnet_name }}"
    subnet: "{{ az_subnet_name }}"
    security_group: "{{ az_secgroup_name }}"
    ip_configurations:
      - name: "{{ az_vm_nic_name }}-conf"
        public_ip_name: "{{ az_public_ip_name }}"

- name: "Create Virtual Machine {{ az_vm_name }}"
  local_action:
    module: azure_rm_virtualmachine
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    availability_set: "{{ az_availabilitysets_name }}"
    name: "{{ az_vm_name }}"
    vm_size: "{{ az_vm_size }}"
    os_type: "{{ az_os_type_vm }}"
    storage_account_name: "{{ az_storageaccount_name }}"
    network_interface_names: "{{ az_vm_nic_name }}"
    admin_username: "{{ az_vm_admin_user }}"
    admin_password: "{{ az_vm_admin_pwd }}"
    managed_disk_type: "{{ az_managed_disk_type }}"
    state: present
    image:
      offer: "{{ az_image_offer }}"
      publisher: "{{ az_image_publisher }}"
      sku: "{{ az_image_sku }}"
      version: "{{ az_image_version }}"
    tags:
      purpose: "{{ az_environment }}"
      application: "{{ az_application }}"
      os: "{{ az_os_type_vm }}"

- name: Add instances to inventory
  local_action:
    module: add_host
    name: "{{ az_vm_name }}"
    ansible_host: "{{ r_azure_public_ip.state.ip_address }}"
    ansible_user: "{{ instance_ansible_user }}"
    ansible_port: "{{ instance_ansible_port }}"
    groups:
      - "az"
      - "{{ instance_role }}"
      - "{{ az_os_type_vm }}"
