---
- name:  Delete {{ az_vm_name }} VM from {{ az_resourcegroup_name }} on {{ az_region }}
  azure_rm_virtualmachine:
    name: "{{ az_vm_name }}"
    resource_group: "{{ az_resourcegroup_name }}"
    location: "{{ az_location }}"
    availability_set: "{{ az_availabilitysets_name }}"
    remove_on_absent: all
    state: absent
  async: 1000
  poll: 15