---
- name:  Delete {{ az_resourcegroup_name }} Resource Group on {{ az_region }}
  azure_rm_resourcegroup:
    location: "{{ az_location }}"
    name: "{{ az_resourcegroup_name }}"
    force: yes
    state: absent
